# примеры API-запросов

@baseUrl = http://localhost:8000

# регистрация
POST {{baseUrl}}/api/register/
Content-Type: application/json

{
  "username": "huhhjkdshjkhjkhjkh",
  "password": "Aa3#11",
  "fullname": "New User",
  "email": "user@domain.com"
}

###

# логин
POST {{baseUrl}}/api/api-token-auth/
Content-Type: application/json

{
  "username": "nshmvaa",
  "password": "Nshmv@1"
}

###

# логин
POST {{baseUrl}}/api-token-auth/
Content-Type: application/json

{
  "username": "Another_User",
  "password": "1111111"
}

###

# логин
POST {{baseUrl}}/api-token-auth/
Content-Type: application/json

{
  "username": "New_User",
  "password": "1111111"
}

###

# получение списка пользователей
GET {{baseUrl}}/users/
Content-Type: application/json
Authorization: Token 5565be1698fc225558fe8abebf19655ba013bf7a

###

# получение пользователя
GET {{baseUrl}}/users/28
Content-Type: application/json
Authorization: Token 5565be1698fc225558fe8abebf19655ba013bf7a

###

# удаление пользователя
DELETE {{baseUrl}}/users/28
Content-Type: application/json
Authorization: Token 5565be1698fc225558fe8abebf19655ba013bf7a

###

# плучение списка файлов
GET {{baseUrl}}/files/
Content-Type: application/json
Authorization: Token 5565be1698fc225558fe8abebf19655ba013bf7a

###

POST {{baseUrl}}/files/
Content-Type: application/json
Authorization: Token 5565be1698fc225558fe8abebf19655ba013bf7a

{
  "file": [{}]
  "original_name": "New file",
  "display_name": "New file name",
  "comment": "Comment"
}
